name: dev-build-deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - uses: actions/aws/cli@master
      - name: install dependencies
        run: yarn
      - name: lint
        run: yarn lint
      - name: tsc
        run: yarn tsc
      - name: tests
        run: CI=true yarn test --passWithNoTests
      - name: build project
        run: yarn build
      - name: build storybook
        run: yarn build-storybook
      - name: deploy the build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 sync build/. s3://dev.cloudkeeper.io/ --delete
